// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewhptelpqqlrqxxgkjcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3aHB0ZWxwcXFscnF4eGdramNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTI5OTcsImV4cCI6MjA2NjM2ODk5N30.r51y9Epv6bWVZ6k4GBWulU61fO5xOn5zGrEKNSinxJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);